# Generated by Django 4.1.3 on 2023-11-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0003_admin_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='mobile_phone',
            field=models.CharField(max_length=15),
        ),
    ]
