# Generated by Django 5.0 on 2023-12-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("p_app", "0005_cart_orders_cartproduct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfume",
            name="p_fragrance",
            field=models.CharField(max_length=50),
        ),
    ]
