# Generated by Django 4.2.5 on 2023-10-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=50)),
                ('p_desc', models.TextField()),
                ('p_fragrance', models.CharField(max_length=30)),
                ('p_quantity', models.PositiveIntegerField()),
                ('p_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('p_image', models.ImageField(upload_to='uploads')),
            ],
        ),
    ]
